### ISSUE TITLE
Modified property doesn't carry over to parent form

### ISSUE THREAD

**Issue by JustMaier** [betsol/angular-input-modified#15]
It appears that child forms do not propagate the `modified` value to their parent forms. I modified one of your examples to show you what I mean: [Example](http://codepen.io/JustMaier/pen/KwJvoy?editors=101)

You'll see that while the modified value of `subForm` changes the modified value of `myForm` (subForm's parent) does not.

**Comment by slavafomin** [comment]
Hello Justin!

Thank you for your interest in this module! I guess your concern is valid. I've never tested this module with nested forms. To be honest, I've never used nested forms in Angular before. I will try to investigate this issue when time permits.

Thank you for PR as well, I will look into your implementation.

**Comment by slavafomin** [comment]
FYI: I'm working on this issue right now. I hope I will make a release soon!

**Comment by slavafomin** [comment]
I'm glad to say that nested forms are now fully supported in minor release `2.1.0`. Feel free to test it and tell me if it works for you. Thank you!

**Comment by slavafomin** [comment]
BTW, here's the demo: http://betsol.github.io/angular-input-modified/nested-forms/.

**Comment by JustMaier** [comment]
Seems to be working great. Thanks for the awesome module!

**Comment by slavafomin** [comment]
I'm glad to help! If you have further questions or ideas — feel free to get in touch with me. Cheers!
