### ISSUE TITLE
Angular annotations.

### ISSUE THREAD

**Issue by atte-backman** [betsol/angular-input-modified#17]
You should annotate everything. Now, when using require.js and optimizing, mangled variables breaks the code regarding this module. I don't want to add angular-input-modified to ngAnnotate grunt task.

**Comment by slavafomin** [comment]
I'm sorry, it is a mistake. All modules in the `./dist` directory should be annotated. I will fix it as soon as possible. Thank you for noticing it!

**Comment by slavafomin** [comment]
Hello @atte-backman! I've fixed annotations in the new `2.0.4` patch release. It should work as expected without prior processing. Sorry for inconvenience and thanks again! Cheers!
