### ISSUE TITLE
I'd like to be able to exclude certain fields of being checked.

### ISSUE THREAD

**Issue by vcardins** [betsol/angular-input-modified#18]

**Comment by slavafomin** [comment]
Please see this section: https://github.com/betsol/angular-input-modified#inputmodifiedconfigprovider

You can do: `inputModifiedConfigProvider.disableGlobally()` to disable the directive by default.

Then add `bs-modifiable` attribute to all input elements you see necessary.

I think I will need to reflect this in documentation and/or demos.

**Comment by vcardins** [comment]
It would be good if we had the opposite. A directive to set whether the field should be tracked.

**Comment by slavafomin** [comment]
Yes, I will try to implement it in the next release. Do you think `bs-modifiable="true/false"` would be a good solution?

**Comment by vcardins** [comment]
To be honest, intuitively I tried this, then I checked the source code and realized that this directive does nothing :). Also, there is an issue validating/comparing null values. I'll try to reproduce again and send details.

**Comment by slavafomin** [comment]
Sure, please create a Plunk to demonstrate the issue. I will look into it. You can fork our plunk from the README. Make sure to use the latest master version of the library though.

**Comment by vcardins** [comment]
Will do later today ... 4:30 in the morning here, going to bed.

**Comment by vcardins** [comment]
For a quick reference:
http://screencast.com/t/o1XgU1UzsrBs
http://screencast.com/t/DXgIl6kMMt
Will create the Plunkr later.

**Comment by slavafomin** [comment]
Thank you @vcardins for a bug report. I think I've fixed it in immediate `2.0.5` release: "Fixed an issue where elements were used without a parent form".

**Comment by vcardins** [comment]
Thanks for the prompt response, excellent. Have you updated bower yet?

**Comment by slavafomin** [comment]
Yes, you can install latest `2.1.0` version via Bower.

**Comment by vcardins** [comment]
That's was fast :) Thanks again, I'll keep testing. Have you implemented the directive to exclude fields from being validated?

**Comment by slavafomin** [comment]
Not yet, but I will try to finish this until the end of the week.

**Comment by vcardins** [comment]
Thanks !!

**Comment by slavafomin** [comment]
Hello! I've implemented the required behavior in version `2.2.0` of the module. Please see the related chapter in the README: https://github.com/betsol/angular-input-modified#excluding-some-fields.

Thank you for a useful feature request!
