### ISSUE TITLE
Not working with forms that are hidden (using ng-if)

### ISSUE THREAD

**Issue by cdjackson** [betsol/angular-input-modified#22]
Firstly, congratulations - this is a great library - Angular should do this by default!

I have some forms that need to be hidden using ng-if when the template loads. Unfortunately I guess the directive doesn't associate with the form when it gets included into the DOM and I get ```Cannot read property '$setPristine' of undefined``` when the data loads.

From the plunk, click "Show Form" then "Load Form"

http://plnkr.co/edit/NoKikD?p=preview

**Comment by slavafomin** [comment]
Thank you for your report @cdjackson and for the kind words!

I will look into this issue when time permits and will get back to you.

Cheers!

**Comment by cdjackson** [comment]
Thanks (and thanks also for the very quick response :) )

**Comment by cdjackson** [comment]
Actually, I'm not sure this is an issue with your library - it might be a scoping issue with ng-if... I'll have a bit more of a look into this...

**Comment by cdjackson** [comment]
Yep- this is an issue with ng-if creating a child scope - seems there's a lot of issues around the web with this one...

Sorry for the confusion.

**Comment by slavafomin** [comment]
Thanks for elaborative work )
I'm still going to look into this: the module shouldn't generate error messages in all circumstances, maybe I will need to safeguard some parts of the code.

**Comment by cdjackson** [comment]
I don’t think the error was in the module - this issue was that the module wasn’t loaded into the scope that the controller was using...

**Comment by slavafomin** [comment]
Yeah, this is probably is not directly related to the module code. However, if you have a solid use-case that you need to implement using this module — please let me know. I will try to figure something out and craft an example.

Cheers!
