### ISSUE TITLE
Put it on npm

### ISSUE THREAD

**Issue by mateatslc** [betsol/angular-input-modified#23]
Can you please register this on www.npmjs.org?

**Comment by slavafomin** [comment]
Hello @mateatslc, this library is not a Node.js package. I'm not sure how you are going to use it in Node environment.

**Comment by mateatslc** [comment]
npm is packed with non-node packages these days.
"The npm Registry is a public collection of packages of open-source code for Node.js, front-end web apps, mobile apps, robots, routers, and countless other needs of the JavaScript community. "(https://www.npmjs.com/about#about-npm)
a node module is just one of the countless things you can publish on npm.
"You can publish any directory that has a package.json file ..." (https://docs.npmjs.com/getting-started/publishing-npm-packages)
thanks in advance, and let me know if I can be of any assistance!

**Comment by slavafomin** [comment]
I've released the NPM package. Thank you for a suggestion. Cheers!

**Comment by mateatslc** [comment]
that was fast. ninja-fast. thanks ;)
