### ISSUE TITLE
ngChange doesn't trigger? / getting data from modal window

### ISSUE THREAD

**Issue by Mr-Negative** [betsol/angular-input-modified#25]
Hi. i need to check if data from modal window form is changed.
if i set it up like this
" ng-model="variation_form.modified"  ng-change="change()" value = "{{ variation_form.modified ? '1' : '0' }}">
then manually changing input value will trigger change function, but changing it via changing  any form element it doesnt trigger. Any help? Could be any workaround . I have function ok() that is closing modalInstance and there i need to access modified value.

**Comment by slavafomin** [comment]
Hello @Mr-Negative!

Thank you for an interest in this module. However, I'm not sure I understood your use case and the problem. Could you please create a Plunk to demonstrate the issue? You can start with this: http://plnkr.co/edit/g2MDXv81OOBuGo6ORvdt?p=preview

Then I will be glad to dig into it and will try to help you.

Cheers!

**Comment by Mr-Negative** [comment]
http://plnkr.co/edit/2NxkIWQnqOOyXjMTdVw3?p=preview when you change value on " Form modified:" input it will trigger alert. when input will change by writing in full name input - it won't

**Comment by slavafomin** [comment]
I see. But, why do you need to bind modification state via `ngModel` and monitor it via `ngChange`? What are you trying to achieve in the end?

**Comment by Mr-Negative** [comment]
First of all im new in angular so maybe question is stupid;-). i have form that is created in modal, and when i click "ok" button i need have information in parent if it was modified. In Your examples you disable save button, i need it to return this data from model to function "ok". if i would do ng-click="ok({{variation_form.modified}})" it generates Error: [$parse:syntax] Syntax Error: Token 'variation_form.modified' is unexpected, expecting [:] at column 6 of the expression [ok({{variation_form.modified}})] starting at [variation_form.modified}})].

**Comment by slavafomin** [comment]
It looks like you've found a very weird way to solve this problem. First of all look at some good module for dialogue windows. Like this one: http://likeastore.github.io/ngDialog/#. Your modal form will run inside of an isolated dialogue scope. You could pass any data from this scope to your parent application via promises. Look at this: https://github.com/likeastore/ngDialog#scopeclosethisdialogvalue.

**Comment by Mr-Negative** [comment]
thx. i'm working on somebody elses code so i can't use this dialog.module but i found workaround and in next projects i will use this module. Thanks for help.

**Comment by slavafomin** [comment]
@Mr-Negative sure thing. The approach should be the same with any other dialogue module if it supports at least the minimal functionality.

**Comment by Mr-Negative** [comment]
It was written by this "dev" :-/.  But i have one question "around this". Is it possible to attach maybe some watch or something like this to modified value at all? it would be usefull for an example triggering custom validators for whole form only when modified

**Comment by slavafomin** [comment]
You should be able to add watches standard way, e.g.: `$scope.$watch('formName.modified', onFormModified);` or `$scope.$watch('formName.fieldName.modified', onFieldModified);`.

**Comment by Mr-Negative** [comment]
Hi i found answer so i put it here so maybe somebody else find this post and find it usefull. $watch doesnt work well with modals  [ui-bootsrap ones] becouse of isolated dialogue scope.  But if you do something like this - https://gist.github.com/rnkoaa/8333940  it would work on this plugin also. 

Most important bit is to name it like this "form.userForm"  and
var ModalInstanceCtrl = function ($scope, $modalInstance, userForm) {
    $scope.form = {}

thx for help and this amazing plugin
