### ISSUE TITLE
regarding the modal

### ISSUE THREAD

**Issue by vikasmundra** [betsol/angular-input-modified#26]
Hello,
I need to know is there any way to use dirty check on modal instead of the form name element. If yes can you please write me the simple example.
And I have also one custom dropdown in my form.
Which is not there the name attributes on my html how can I track this.
I have past my html in the below mail.
Can you please see the below html and provide me the function in my JavaScript  to check the dirty flag

<div id="modalFieldDetail">
                <header>
                                <h5>Field Details</h5>
                                <i class="close-reveal-modal" data-ng-click="cancel()"></i>
                </header>
                <section>
                                <form id="fieldDetailForm" name="dummy.fieldDetailForm" novalidate>
                                                <div class="field-summary-wrapper clearfix">
                                                                <fieldset class="field-summary">
                                                                                <p>
                                                                                                <label>Field Name <span class="mandatorty" >*</span></label>
                                                                                </p>
                                                                                <p>
                                                                                                <input type="text" id="fieldName" name="fieldName" data-ng-model="fieldData.name" data-ng-pattern="/^(\w|_|(\w \w)|( \w)|(\w ))+$/" maxlength="50" minlength="1" autofocus />
                                                                                </p>
                                                                                <p>
                                                                                                <label>Farm Name <span class="mandatorty">*</span></label>
                                                                                </p>
                                                                                <p>
                                                                                                <div class="custom-list farm-list" dropdown-select="farmsList" dropdown-model="selectedFarm" dropdown-item-label="name" dropdown-onchange="toggleFarmDeleteBtn()" ></div>
                                                                                                <i data-ng-click="createFarm()" class="field-option-icon field-add-icon" title="Create New Farm"></i>
                                                                                                <i data-ng-click="updateFarm()" class="field-option-icon field-edit-icon" title="Edit Farm"></i>
                                                                                                <i data-ng-click="deleteFarm()" class="animate-if field-option-icon field-delete-icon" data-ng-if="isShowDeleteFarm" title="Delete Farm"></i>
                                                                                </p>
                                                                </fieldset>
                                                                <div class="field-highlights">
                                                                                <figure class="clearfix">
                                                                                                <small class="crop-icon {{cropsListSelectedP0.name.toLowerCase().split(' ').join('')}}" alt={{cropsListSelectedP0.name}} title={{cropsListSelectedP0.name}}></small>
                                                                                                <figcaption>
                                                                                                                <em>{{acreage.toFixed(2)}}</em>
                                                                                                                <strong>{{fieldUnit | uppercase}}</strong>
                                                                                                </figcaption>
                                                                                </figure>
                                                                </div>
                                                </div>
                                                <div class="field-accordion-wrapper clearfix">
                                                  <accordion close-others="oneAtATime">
                                                    <accordion-group is-open="true">
                                                                                <accordion-heading>
                                                                                <div class="row season-header">
                                                                                                  <div class="small-6 large-6 columns">Current Season ({{seasonsName[0].substr(0,4)}} / {{seasonsName[0].substr(5)}})</div>
                                                                                                  <div class="small-6 large-6 columns prev-season-head">Previous Season ({{seasonsName[1].substr(0,4)}} / {{seasonsName[1].substr(5)}}) <i class="accord-open-icon right"></i></div>
                                                                                </div>
                                                                                </accordion-heading>
                                                      <div class="season-columns clearfix">
                                                                                                <fieldset class="current-season" data-ng-if="seasonsName[0]">
                                                                                                                <div class="list-data">
                                                                                                                                <label>Crop <span class="mandatorty">*</span></label>
                                                                                                                                <div class="custom-list cbv-list" dropdown-select="cropsList" dropdown-model="cropsListSelectedP0" dropdown-item-label="name" dropdown-onchange="resetProductsList(0);resetVarietyDetail(varitiesListSelectedP01, 0, 1);resetVarietyDetail(varitiesListSelectedP02, 0, 2);"></div>
                                                                                                                </div>
                                                                                                                <div>
                                                                                                                                <label>Planting Date <span class="mandatorty">*</span></label>
                                                                                                                                <input type="text" readonly="readonly" class="datepicker" id="sowingDateP0" data-ng-model="fieldSeasonData[0].sowingDate" datepicker data-mindate="09/02/{{seasonsName[0].substr(0,4)}}" data-maxdate="09/01/{{seasonsName[0].substr(5)}}"  />
                                                                                                                </div>
                                                                                                                <div class="list-data">
                                                                                                                                <label>Brand</label>
                                                                                                                                <div class="custom-list cbv-list" data-ng-class="{'disabled-dd': (brandsList0.length <= 0)}" dropdown-select="brandsList0" dropdown-model="brandsListSelectedP01" dropdown-item-label="name" dropdown-onchange="resetProductsList(0,'1');resetVarietyDetail(varitiesListSelectedP01, 0, 1);"></div>
                                                                                                                                <i class="field-option-icon field-add-icon" data-ng-click="addNewFieldsCurrent()" data-ng-if="!newFieldsPrev0Show" title="Add Second Brand" ng-class="{'disabled-icon' : (varitiesListSelectedP01.id ? false : true)}"></i>
                                                                                                                </div>
                                                                                                                <div class="list-data">
                                                                                                                                <label>Product</label>
                                                                                                                                <div class="custom-list cbv-list" data-ng-class="{'disabled-dd': (varitiesList01.length <= 0)}" dropdown-select="varitiesList01" dropdown-model="varitiesListSelectedP01" dropdown-item-label="name" dropdown-onchange="resetVarietyDetail(varitiesListSelectedP01, 0, 1)"></div>
                                                                                                                                <i class="field-option-icon field-add-icon" data-ng-click="addNewFieldsCurrent()" data-ng-if="!newFieldsPrev0Show" title="Add Second Product" ng-class="{'disabled-icon' : (varitiesListSelectedP01.id ? false : true)}"></i>
                                                                                                                </div>
                                                                                                                <div class="season-prod-details" data-ng-if="prodDetailsShow01">
                                                                                                                                <label>Product Details</label>
                                                                                                                                <span>RTP-{{varietyDetailP01.rtp}} ; RTN-{{varietyDetailP01.rtn}} ; RTCC-{{varietyDetailP01.rtcc}}</span>
                                                                                                                </div>
                                                                                                                <div>
                                                                                                                                <label>Average Population</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[0].averagePopulation" class="yield-or-pop" maxlength="11" number-and-dot='{"decimalPlace":2}' money-input/>
                                                                                                                </div>
                                                                                                                <div class="product-sheet-links">
                                                                                                                                <a class="animate-if" href="#" data-ng-if="isProdImageAvail01" data-ng-click="openProductImagesPopup(varietyDetailP01.varietyPics, varitiesListSelectedP01.name,varitiesListSelectedP01.id)">Product Images</a>
                                                                                                                                <a class="animate-if" href="#" data-ng-if="isTechSheetAvail01" data-ng-click="downloadTechSheet(varitiesListSelectedP01.id)">Tech Sheets</a>
                                                                                                                </div>
                                                                                                                <div class="animate-if list-data" data-ng-if="newFieldsPrev0Show">
                                                                                                                                <label>Brand</label>
                                                                                                                                <div class="custom-list cbv-list" data-ng-class="{'disabled-dd': (brandsList0.length <= 0)}" dropdown-select="brandsList0" dropdown-model="brandsListSelectedP02" dropdown-item-label="name" dropdown-onchange="resetProductsList(0,'2');resetVarietyDetail(varitiesListSelectedP02, 0, 2)"></div>
                                                                                                                                <i class="field-option-icon field-delete-icon" data-ng-click="removeAdditionalProductFromCurrentSeason()" title="Delete Second Brand"></i>
                                                                                                                </div>
                                                                                                                <div class="animate-if list-data" data-ng-if="newFieldsPrev0Show">
                                                                                                                                <label>Product</label>
                                                                                                                                <div class="custom-list cbv-list" data-ng-class="{'disabled-dd': (varitiesList02.length <= 0)}" dropdown-select="varitiesList02" dropdown-model="varitiesListSelectedP02" dropdown-item-label="name" dropdown-onchange="resetVarietyDetail(varitiesListSelectedP02, 0, 2)"></div>
                                                                                                                                <i class="field-option-icon field-delete-icon" data-ng-click="removeAdditionalProductFromCurrentSeason()" title="Delete Second Product"></i>
                                                                                                                </div>
                                                                                                                <div class="season-prod-details" data-ng-if="prodDetailsShow02 && newFieldsPrev0Show">
                                                                                                                                <label>Product Details</label>
                                                                                                                                <span>RTP-{{varietyDetailP02.rtp}} ; RTN-{{varietyDetailP02.rtn}} ; RTCC-{{varietyDetailP02.rtcc}}</span>
                                                                                                                </div>
                                                                                                                <div class="animate-if" data-ng-if="newFieldsPrev0Show">
                                                                                                                                <label>Average Population</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[0].averagePopulation2" class="yield-or-pop"  maxlength="11" number-and-dot='{"decimalPlace":2}' money-input/>
                                                                                                                </div>
                                                                                                                <div class="product-sheet-links" data-ng-if="newFieldsPrev0Show">
                                                                                                                                <a class="animate-if" href="#" data-ng-if="isProdImageAvail02" data-ng-click="openProductImagesPopup(varietyDetailP02.varietyPics, varitiesListSelectedP02.name,varitiesListSelectedP02.id)">Product Images</a>
                                                                                                                                <a class="animate-if" href="#" data-ng-if="isTechSheetAvail02" data-ng-click="downloadTechSheet(varitiesListSelectedP02.id)">Tech Sheets</a>
                                                                                                                </div>
                                                                                                </fieldset>
                                                                                                <fieldset class="prev-season border-fixer" data-ng-if="seasonsName[1]">
                                                                                                                <div class="list-data">
                                                                                                                                <label>Crop <span class="mandatorty">*</span></label>
                                                                                                                                <div class="custom-list cbv-list" dropdown-select="cropsList" dropdown-model="cropsListSelectedP1" dropdown-item-label="name" dropdown-onchange="resetProductsList(1);resetVarietyDetail(varitiesListSelectedP11, 1, 1);resetVarietyDetail(varitiesListSelectedP12, 1, 2)" confirm-message="Crop change will clear assigned brand and product." check-before-dropdown-clicked="cropExistsP1" disable-dropdown="false"></div>
                                                                                                                </div>
                                                                                                                <div>
                                                                                                                                <label>Planting Date <span class="mandatorty">*</span></label>
                                                                                                                                <input type="text" readonly="readonly" class="datepicker" id="sowingDateP1" data-ng-model="fieldSeasonData[1].sowingDate" datepicker data-mindate="09/02/{{seasonsName[1].substr(0,4)}}" data-maxdate="09/01/{{seasonsName[1].substr(5)}}" />
                                                                                                                </div>
                                                                                                                <div class="list-data">
                                                                                                                                <label>Brand</label>
                                                                                                                                <input type="text" data-ng-model="brandsListSelectedP11.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div class="list-data">
                                                                                                                                <label>Product</label>
                                                                                                                                <input type="text" data-ng-model="varitiesListSelectedP11.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div class="season-prod-details" data-ng-if="prodDetailsShow11">
                                                                                                                                <label>Product Details</label>
                                                                                                                                <span>RTP-{{varietyDetailP11.rtp}} ; RTN-{{varietyDetailP11.rtn}} ; RTCC-{{varietyDetailP11.rtcc}}</span>
                                                                                                                </div>
                                                                                                                <div>
                                                                                                                                <label>Average Population</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[1].averagePopulation" class="yield-or-pop" maxlength="11" number-and-dot='{"decimalPlace":2}' money-input/>
                                                                                                                </div>
                                                                                                                <div>
                                                                                                                                <label>Observed Yield</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[1].observedYield" class="yield-or-pop" number-and-dot='{"decimalPlace":1}' maxlength="9"/>
                                                                                                                </div>
                                                                                                                <div class="product-sheet-links">
                                                                                                                                <a class="animate-if" href="#" data-ng-if="isProdImageAvail11" data-ng-click="openProductImagesPopup(varietyDetailP11.varietyPics, varitiesListSelectedP11.name,varitiesListSelectedP11.id)">Product Images</a>
                                                                                                                                <a class="animate-if" href="#" data-ng-if="isTechSheetAvail11" data-ng-click="downloadTechSheet(varitiesListSelectedP11.id)">Tech Sheets</a>
                                                                                                                </div>
                                                                                                                <div class="animate-if list-data" data-ng-if="newFieldsPrev1Show">
                                                                                                                                <label>Brand</label>
                                                                                                                                <input type="text" data-ng-model="brandsListSelectedP12.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div class="animate-if list-data" data-ng-if="newFieldsPrev1Show">
                                                                                                                                <label>Product</label>
                                                                                                                                <input type="text" data-ng-model="varitiesListSelectedP12.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div class="season-prod-details" data-ng-if="prodDetailsShow12">
                                                                                                                                <label>Product Details</label>
                                                                                                                                <span>RTP-{{varietyDetailP12.rtp}} ; RTN-{{varietyDetailP12.rtn}} ; RTCC-{{varietyDetailP12.rtcc}}</span>
                                                                                                                </div>
                                                                                                                <div class="animate-if" data-ng-if="newFieldsPrev1Show">
                                                                                                                                <label>Average Population</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[1].averagePopulation2" class="yield-or-pop" number-and-dot='{"decimalPlace":2}' maxlength="11" money-input/>
                                                                                                                </div>
                                                                                                                <div class="product-sheet-links">
                                                                                                                                <a class="animate-if" href="#" data-ng-if="isProdImageAvail12" data-ng-click="openProductImagesPopup(varietyDetailP12.varietyPics, varitiesListSelectedP12.name,varitiesListSelectedP12.id)">Product Images</a>
                                                                                                                                <a class="animate-if" href="#" data-ng-if="isTechSheetAvail12" data-ng-click="downloadTechSheet(varitiesListSelectedP12.id)">Tech Sheets</a>
                                                                                                                </div>
                                                                                                </fieldset>
                                                                                </div>
                                                    </accordion-group>
                                                    <accordion-group data-ng-if="seasonsName[2]">
                                                                                <accordion-heading>
                                                                                                <div class="row season-header">
                                                                                                                  <div class="small-12 large-12 columns">{{seasonsName[2].substr(0,4)}} / {{seasonsName[2].substr(5)}} Season <i class="accord-open-icon right"></i></div>
                                                                                                </div>
                                                                                </accordion-heading>
                                                                   <div class="season-columns old-season clearfix">
                                                                                                <fieldset class="season-col-left">
                                                                                                                <div>
                                                                                                                                <label>Planting Date <span ng-if="cropsListSelectedP2.name" class="mandatorty">*</span></label>
                                                                                                                                <input type="text" readonly="readonly" id="sowingDateP2" date-disabled="!cropsListSelectedP2.name" class="datepicker" data-ng-model="fieldSeasonData[2].sowingDate" datepicker data-mindate="09/02/{{seasonsName[2].substr(0,4)}}" data-maxdate="09/01/{{seasonsName[2].substr(5)}}" />
                                                                                                                </div>
                                                                                                                <div class="list-data">
                                                                                                                                <label>Crop <span class="mandatorty"></span></label>
                                                                                                                                <div class="custom-list cbv-list" dropdown-select="cropsList" dropdown-model="cropsListSelectedP2" dropdown-item-label="name" dropdown-onchange="resetProductsList(2)" confirm-message="Crop change will clear assigned brand and product." check-before-dropdown-clicked="cropExistsP2" disable-dropdown="false"></div>
                                                                                                                </div>
                                                                                                                <div class="list-data">
                                                                                                                                <label>Brand</label>
                                                                                                                                <input type="text" data-ng-model="brandsListSelectedP21.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div class="list-data">
                                                                                                                                <label>Product</label>
                                                                                                                                <input type="text" data-ng-model="varitiesListSelectedP21.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div>
                                                                                                                                <label>Average Population</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[2].averagePopulation" class="yield-or-pop" number-and-dot='{"decimalPlace":2}' maxlength="11" money-input/>
                                                                                                                </div>
                                                                                                </fieldset>
                                                                                                <fieldset class="season-col-right">
                                                                                                                <div>
                                                                                                                                <label>Observed Yield</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[2].observedYield" class="yield-or-pop" number-and-dot='{"decimalPlace":1}' maxlength="9"/>
                                                                                                                </div>
                                                                                                                <div class="animate-if list-data" data-ng-if="newFieldsPrev2Show">
                                                                                                                                <label>Brand</label>
                                                                                                                                <input type="text" data-ng-model="brandsListSelectedP22.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div class="animate-if list-data" data-ng-if="newFieldsPrev2Show">
                                                                                                                                <label>Product</label>
                                                                                                                                <input type="text" data-ng-model="varitiesListSelectedP22.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div class="animate-if" data-ng-if="newFieldsPrev2Show">
                                                                                                                                <label>Average Population</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[2].averagePopulation2" class="yield-or-pop" number-and-dot='{"decimalPlace":2}' maxlength="11" money-input/>
                                                                                                                </div>
                                                                                                </fieldset>
                                                                                </div>
                                                    </accordion-group>
                                                    <accordion-group data-ng-if="seasonsName[3]">
                                                                                <accordion-heading>
                                                                                                <div class="row season-header">
                                                                                                                  <div class="small-12 large-12 columns">{{seasonsName[3].substr(0,4)}} / {{seasonsName[3].substr(5)}} Season <i class="accord-open-icon right"></i></div>
                                                                                                </div>
                                                                                </accordion-heading>
                                                                   <div class="season-columns old-season clearfix">
                                                                                                <fieldset class="season-col-left">
                                                                                                                <div>
                                                                                                                                <label>Planting Date <span ng-if="cropsListSelectedP3.name" class="mandatorty">*</span></label>
                                                                                                                                <input type="text" readonly="readonly" id="sowingDateP3" date-disabled="!cropsListSelectedP3.name" class="datepicker" data-ng-model="fieldSeasonData[3].sowingDate" datepicker data-mindate="09/02/{{seasonsName[3].substr(0,4)}}" data-maxdate="09/01/{{seasonsName[3].substr(5)}}" />
                                                                                                                </div>
                                                                                                                <div class="list-data">
                                                                                                                                <label>Crop <span class="mandatorty"></span></label>
                                                                                                                                <div class="custom-list cbv-list" dropdown-select="cropsList" dropdown-model="cropsListSelectedP3" dropdown-item-label="name" dropdown-onchange="resetProductsList(3)" confirm-message=" Crop change will clear assigned brand and product." check-before-dropdown-clicked="cropExistsP3" disable-dropdown="false"></div>
                                                                                                                </div>
                                                                                                                <div class="list-data">
                                                                                                                                <label>Brand</label>
                                                                                                                                <input type="text" data-ng-model="brandsListSelectedP31.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div class="list-data">
                                                                                                                                <label>Product</label>
                                                                                                                                <input type="text" data-ng-model="varitiesListSelectedP31.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div>
                                                                                                                                <label>Average Population</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[3].averagePopulation" class="yield-or-pop" number-and-dot='{"decimalPlace":2}' maxlength="11" money-input/>
                                                                                                                </div>
                                                                                                </fieldset>
                                                                                                <fieldset class="season-col-right">
                                                                                                                <div>
                                                                                                                                <label>Observed Yield</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[3].observedYield" class="yield-or-pop" number-and-dot='{"decimalPlace":1}' maxlength="9"/>
                                                                                                                </div>
                                                                                                                <div class="animate-if list-data" data-ng-if="newFieldsPrev3Show">
                                                                                                                                <label>Brand</label>
                                                                                                                                <input type="text" data-ng-model="brandsListSelectedP32.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div class="animate-if list-data" data-ng-if="newFieldsPrev3Show">
                                                                                                                                <label>Product</label>
                                                                                                                                <input type="text" data-ng-model="varitiesListSelectedP32.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div class="animate-if" data-ng-if="newFieldsPrev3Show">
                                                                                                                                <label>Average Population</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[3].averagePopulation2" class="yield-or-pop" number-and-dot='{"decimalPlace":2}' maxlength="11" money-input/>
                                                                                                                </div>
                                                                                                </fieldset>
                                                                                </div>
                                                    </accordion-group>
                                                    <accordion-group data-ng-if="seasonsName[4]">
                                                                                <accordion-heading>
                                                                                                <div class="row season-header">
                                                                                                                  <div class="small-12 large-12 columns">{{seasonsName[4].substr(0,4)}} / {{seasonsName[4].substr(5)}} Season <i class="accord-open-icon right"></i></div>
                                                                                                </div>
                                                                                </accordion-heading>
                                                                   <div class="season-columns old-season clearfix">
                                                                                                <fieldset class="season-col-left">
                                                                                                                <div>
                                                                                                                                <label>Planting Date <span ng-if="cropsListSelectedP4.name" class="mandatorty">*</span></label>
                                                                                                                                <input type="text" readonly="readonly" id="sowingDateP4" date-disabled="!cropsListSelectedP4.name" class="datepicker" data-ng-model="fieldSeasonData[4].sowingDate" datepicker data-mindate="09/02/{{seasonsName[4].substr(0,4)}}" data-maxdate="09/01/{{seasonsName[4].substr(5)}}" />
                                                                                                                </div>
                                                                                                                <div class="list-data">
                                                                                                                                <label>Crop <span class="mandatorty"></span></label>
                                                                                                                                <div class="custom-list cbv-list" dropdown-select="cropsList" dropdown-model="cropsListSelectedP4" dropdown-item-label="name" dropdown-onchange=" resetProductsList(4)" confirm-message="Crop change will clear assigned brand and product." check-before-dropdown-clicked="cropExistsP4" disable-dropdown="false"></div>
                                                                                                                </div>
                                                                                                                <div class="list-data">
                                                                                                                                <label>Brand</label>
                                                                                                                                <input type="text" data-ng-model="brandsListSelectedP41.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div class="list-data">
                                                                                                                                <label>Product</label>
                                                                                                                                <input type="text" data-ng-model="varitiesListSelectedP41.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div>
                                                                                                                                <label>Average Population</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[4].averagePopulation" class="yield-or-pop" number-and-dot='{"decimalPlace":2}' maxlength="11" money-input/>
                                                                                                                </div>
                                                                                                </fieldset>
                                                                                                <fieldset class="season-col-right">
                                                                                                                <div>
                                                                                                                                <label>Observed Yield</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[4].observedYield" class="yield-or-pop" number-and-dot='{"decimalPlace":1}' maxlength="9"/>
                                                                                                                </div>
                                                                                                                <div class="animate-if list-data" data-ng-if="newFieldsPrev4Show">
                                                                                                                                <label>Brand</label>
                                                                                                                                <input type="text" data-ng-model="brandsListSelectedP42.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div class="animate-if list-data" data-ng-if="newFieldsPrev4Show">
                                                                                                                                <label>Product</label>
                                                                                                                                <input type="text" data-ng-model="varitiesListSelectedP42.name" readonly="readonly"/>
                                                                                                                                
                                                                                                                </div>
                                                                                                                <div class="animate-if" data-ng-if="newFieldsPrev4Show">
                                                                                                                                <label>Average Population</label>
                                                                                                                                <input type="text" data-ng-model="fieldSeasonData[4].averagePopulation2" class="yield-or-pop" number-and-dot='{"decimalPlace":2}' maxlength="11" money-input/>
                                                                                                                </div>
                                                                                                </fieldset>
                                                                                </div>
                                                    </accordion-group>
                                                  </accordion>
                                                </div>
                                                <div class="btn-container">
                                                                <button type="submit" class="button-small right" data-ng-click="createOrUpdate()">Save</button>
                                                </div>
                                </form>
                </section>
</div>

**Comment by slavafomin** [comment]
Hello @vikasmundra. Thank you for your interest in the library.

What do you mean by doing "dirty check on modal"? Dirty state of the `ngModel` or `ngForm` can be checked using Angular's `$dirty`/`$pristine` properties, `input-modified` has nothing to do with this.

Every element that you want to "track" using `input-modified` should have a correct `name` property. Otherwise you will not be able to fetch it using `$scope.formName.fieldName` notation. However, maybe you will be able to retrieve the controller using this suggestion: https://groups.google.com/forum/#!topic/angular/BZqs4TXyOcw. I'm not tried it and I don't know if it's a public API though. Maybe you should find a way to specify name for the underlying input field of the used directive. if not possible consider to file an issue for that module.

The issues here on GitHub is primarily for solving problems with the library itself. If you need additional help with your project — I'm providing consulting services on a commercial basis. Feel free to contact me by E-Mail for this: s.fomin@betsol.ru.

Cheers!
