### ISSUE TITLE
When using select ng-modified isn't set to true until the second click.

### ISSUE THREAD

**Issue by nvernooy** [betsol/angular-input-modified#27]
I'm not sure if I had a special case, cause I was using ui-select (https://github.com/angular-ui/ui-select) in a bootstrap modal. The model is initially set to undefined and the array using for the options is only loaded when the modal is opened. 
On opening the modal the modified value was set to false, which is fine, then when a value is selected in the select, it stays false, only when another value is selected was it set to true.

I was able to fix it by checking if the $modelValue was defined in the onInputValueChange function, like so:

                  if ('undefined' === typeof ngModel.masterValue) {
                        // Initializing the master value.
                        ngModel.masterValue = ngModel.$modelValue;
                        // if the master value has a value, set modified to true
                        if (ngModel.masterValue){
                            ngModel.modified = true;
                        }
                        // Initially decorating the element.
                        toggleCssClasses();

                    } else {
                         ...
                    }

**Comment by slavafomin** [comment]
Could you please create a small demo of the issue using our Plunk: http://plnkr.co/edit/g2MDXv81OOBuGo6ORvdt?p=preview ?

**Comment by nvernooy** [comment]
I've only tried to reproduce the error now, but I could not get it to show in the plunk. Then I saw the angular-input-modified.js file I was using was different from the one in the plunk, so it seems like it has been fixed.
