### ISSUE TITLE
AngularUI Bootstrap DatePicker & TimePicker Example Broken

### ISSUE THREAD

**Issue by bbodenmiller** [betsol/angular-input-modified#31]
The example shown at https://betsol.github.io/angular-input-modified/bootstrap-ui-date-and-time/ appears to be broken using Chrome 46.0.2490.80 m.

Related to #4.

**Comment by slavafomin** [comment]
Hello @bbodenmiller!

Thank you for noticing! I've updated the demo. It should work now,

Cheers!
