### ISSUE TITLE
Consider renaming "modified" to "$modified"

### ISSUE THREAD

**Issue by jrharshath** [betsol/angular-input-modified#34]
This is only a suggestion. Since:
- since we're modifying `ng-model`'s native behaviour
- not declaring a new directive
- calling the module `ngInputModified` instead of something that's not in angular's namespace (like bsInputModified)
- overriding the way `$pristine` is set to account for `modified` (again affecting angular's standard behaviour)

I propose we call our flag `$modified`. It would feel like a very fluid extension of angular's capabilities this way.

Let me know what you think!

**Comment by slavafomin** [comment]
Yes, Harshath. That makes sense.
However, I'm not yet sure in what direction should we move - to make this module closer to the Angular.js codebase or to make it a more independent third-party extension.
We'll think about it, if we'll decide to make a 2.0 release.

**Comment by jrharshath** [comment]
Perhaps convert this into a PR for angularjs first, and then see how it turns out? :smile:

**Comment by jrharshath** [comment]
Angular already finds this feature wanting - check out this issue.

https://github.com/angular/angular.js/issues/11289

**Comment by slavafomin** [comment]
I've decided to stick to the current naming scheme for now. We should interfere with Angular namespace as little as possible.
