### ISSUE TITLE
Add support for CommonJS

### ISSUE THREAD

**Issue by slavafomin** [betsol/angular-input-modified#37]
As stated in #36. Make sure that it works with [webpack module bundler](https://webpack.github.io/).

**Comment by slavafomin** [comment]
I've introduced support for CommonJS module system.

@venkateshsampath could you please try it?

You will need to add dependency to your project first:

`npm i --save-dev https://github.com/betsol/angular-input-modified.git#master`

Then, use it in your entry file:

```javascript
'use strict';

var app = angular
  .module('app', [
    require('angular-input-modified')
  ])
  .config(function (inputModifiedConfigProvider) {
    inputModifiedConfigProvider
      .disableGlobally()
    ;
  })
;
```

**Comment by venkateshsampath** [comment]
Hi @slavafomin,
Sorry for this delayed response. Thanks for adding the commonjs package manager support.
Will check it with my project today and get back to you ASAP.

**Comment by venkateshsampath** [comment]
Hi @slavafomin,

Thank you so much for the fix.
The fix worked perfectly fine with my project that uses webpack. 

Will you be able to publish a new version as npm module so that I could use it after updating my package.json.

**Comment by slavafomin** [comment]
Here goes the `2.3.2`, have fun!

**Comment by venkateshsampath** [comment]
Awesome! Thanks @slavafomin.
