### ISSUE TITLE
Angular 2 support?

### ISSUE THREAD

**Issue by gandaldf** [betsol/angular-input-modified#44]
Your plugin saved my life, are you planning to port it to Angular 2?

**Comment by slavafomin** [comment]
Thank you @gandaldf!

I'm not using Angular 2 yet myself, so I can't return any promises to you at this moment ; )

**Comment by Moustafa20** [comment]
any updates for this issue?

**Comment by slavafomin** [comment]
@moustafa20 feel free to port it.

**Comment by Moustafa20** [comment]
@slavafomin Thanks for your reply
hope you are ready to provide your awesome plugins to support Angular 2 soon
Regards

**Comment by slavafomin** [comment]
@moustafa20 I've actually switched to Angular recently, so I will consider implementing it, if time permits of course.

**Comment by Moustafa20** [comment]
@slavafomin greate news , sounds like good :)
