### ISSUE TITLE
Issues with input type=email

### ISSUE THREAD

**Issue by CanKattwinkel** [betsol/angular-input-modified#49]
Hello,

`<input type="email">` will remain "not modified" until a valid e-mail is entered. 

So if you change the mail in the plunker to any invalid string like  "notvalidmail!", then the modified value will remain false while it should be true since the value has changed!

![image](https://cloud.githubusercontent.com/assets/11500619/20039210/7abff3dc-a440-11e6-8c7a-1c412812287d.png)

http://plnkr.co/edit/a923ORQwFMPv4f568iwz

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

However, this is the way Angular (ngModelController) handles input. See the documentation here:
https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#$setViewValue

To alter this behavior you could pass `allowInvalid: true` to the [ngModelOptions](https://docs.angularjs.org/api/ng/directive/ngModelOptions).

See the Plunk below for example:
http://plnkr.co/edit/HnSymCtQSlLRPCpHK69g?p=preview

Does this answer your question?
