### ISSUE TITLE
Issues with ng-repeat

### ISSUE THREAD

**Issue by prudd** [betsol/angular-input-modified#5]
Unfortunately I have discovered another issue with this library. If you are using an ng-repeat it does not check if the entire form has been modified correctly.

I have an Plunk here as an example: http://plnkr.co/edit/b7OTGt6NTYIJDJIEHMe0?p=preview

If you change both fields and then change one back to the original value it thinks the entire form has not been modified. This is because you are adding models to your modified-models array based on the string used in the ng-model tag and not the actual object.

I also tried to use nested forms using the ng-form directive, however the top form does not see that its child forms have been modified.

Thanks for all the help.

**Comment by slavafomin** [comment]
Hello @prudd! I've released a new major version. Feel free to try it out and let me know if further support is required. Thanks!
