### ISSUE TITLE
$$onChildModelModifiedStateChanged

### ISSUE THREAD

**Issue by sandeesaripalli** [betsol/angular-input-modified#54]
Hi,
I am getting this console error though it's not causing any issues, 
Cannot read property '$$onChildModelModifiedStateChanged' of null

Please let me know how to fix this bug.

Regards

Sandeep

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

I wasn't been able to reproduce the issue, but nevertheless I've added an additional guard around this method call for edge cases. Please update to the latest version and let me know if it solves the issue for you.

Cheers!

**Comment by sandeesaripalli** [comment]
It works, Thank you for the quick reply.

Regards

Sandeep

**Comment by slavafomin** [comment]
Nice to hear that @sandeesaripalli! Have a great day!
