### ISSUE TITLE
How do I know why the form is marked as modified?

### ISSUE THREAD

**Issue by sakovias** [betsol/angular-input-modified#55]
I have a form that has some regular `input` fields and some drop-downs that use [angular-ui-select](https://github.com/angular-ui/ui-select). The modified state of regular inputs are easy to track via `form.field.modified`, but the drop-downs don't seem to have such an option.

Is there a way to inspect why the form gets set as modified? I'm trying to call `form.$setPristine()` in a number of places, but that doesn't help get the form cleared. Just need some debugging tools to understand what is going on.

**Comment by sakovias** [comment]
Should be labeled as a question, not really an issue with this repo 😃

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

The `angular-input-modified` is working with `ngModelController`, so your custom or third-party component should implement it. If your component is not using `ngModel` then it's not possible to integrate it properly with the form and with this module. So your question is really `How do you access ngModelController` of the `angular-ui-select`.

**Comment by sakovias** [comment]
True, I'll have figure out how `angular-ui-select` works. The form is marked as modified correctly though.

I was running into a problem multiple times when I didn't know what was modified and the form had too many fields to debug each one quickly. Would be nice to have an option to show all modified fields in a form, something like `form.getModifiedFields()`.

**Comment by slavafomin** [comment]
Please see here:
https://github.com/betsol/angular-input-modified/blob/master/src/directive/form.js#L36

Your form controller should has `modifiedModels` property with the list of all modified `ngModelController`'s. However, if you have nested forms you will have to traverse the tree using `modifiedChildForms` as well.
