### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by developer707** [betsol/angular-input-modified#56]
This Error appears in the console at the start of my application.

`bower-combined.js:5 TypeError: Cannot read property '$$onChildModelModifiedStateChanged' of null`

![image](https://user-images.githubusercontent.com/23486013/27036611-02dbd848-4f4b-11e7-91b6-f9d15ddc9f91.png)

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

What version are you using?

**Comment by developer707** [comment]
Good morning, I am suing version 2.4.1

**Comment by slavafomin** [comment]
This error was fixed recently: https://github.com/betsol/angular-input-modified/issues/54

Make sure to use the latest version of the module (try to re-install it).

**Comment by slavafomin** [comment]
Well, actually there was a problem with release `2.4.1` for some reason. I've released `2.4.2` just now. Please try to update and let me know if it helps. Cheers!

**Comment by developer707** [comment]
Yes it appears to solve the issure Thanks!

**Comment by slavafomin** [comment]
Good to know! Have a nice day!
