### ISSUE TITLE
Doesn't work when bound object member isn't set

### ISSUE THREAD

**Issue by cyates81** [betsol/angular-input-modified#8]
Please see this fork of your plunkr and try changing the about field.  The first letter you type gets set as the masterValue but this is incorrect, it should be null.

http://plnkr.co/edit/04vdPuSYFUE7a7U2ngWE?p=preview

**Comment by cyates81** [comment]
Here's a new plunkr showing the difference.  It requires you to call $setPristine on the form after you load.  http://plnkr.co/edit/YVX4DZaQFnTt2zeqHLNi?p=preview

**Comment by slavafomin** [comment]
Hello @cyates81!

Thank you for a bug-report. I will take a look at it and will get back to you.

**Comment by slavafomin** [comment]
Yes, your concern was perfectly valid. I've changed master value initialization logic to allow a wider usage scenario. Your Plunk should work fine now.

Thanks again for observation. If you have any further concerns regarding this issue - please let me know.

I will include these changes in the upcoming release.

**Comment by slavafomin** [comment]
I've released a new major version. Feel free to try it out and let me know if further support is required. Thanks!
